-- Additive performance indexes for the production PostgreSQL database.
BEGIN;
CREATE INDEX IF NOT EXISTS "ClassMembership_classId_roleInClass_idx" ON "ClassMembership"("classId", "roleInClass");
CREATE INDEX IF NOT EXISTS "StudentProfile_classId_prepYear_idx" ON "StudentProfile"("classId", "prepYear");
CREATE INDEX IF NOT EXISTS "StudentAvailabilitySlot_studentId_dayOfWeek_idx" ON "StudentAvailabilitySlot"("studentId", "dayOfWeek");
CREATE INDEX IF NOT EXISTS "Chapter_subjectId_idx" ON "Chapter"("subjectId");
CREATE INDEX IF NOT EXISTS "Resource_classId_createdAt_idx" ON "Resource"("classId", "createdAt");
CREATE INDEX IF NOT EXISTS "Resource_uploaderId_createdAt_idx" ON "Resource"("uploaderId", "createdAt");
CREATE INDEX IF NOT EXISTS "Resource_subjectId_chapterId_idx" ON "Resource"("subjectId", "chapterId");
CREATE INDEX IF NOT EXISTS "ResourceAccess_resourceId_userId_idx" ON "ResourceAccess"("resourceId", "userId");
CREATE INDEX IF NOT EXISTS "ResourceAccess_classId_idx" ON "ResourceAccess"("classId");
CREATE INDEX IF NOT EXISTS "ResourceAIOutput_resourceId_userId_createdAt_idx" ON "ResourceAIOutput"("resourceId", "userId", "createdAt");
CREATE INDEX IF NOT EXISTS "FlashcardDeck_ownerUserId_createdAt_idx" ON "FlashcardDeck"("ownerUserId", "createdAt");
CREATE INDEX IF NOT EXISTS "FlashcardDeck_parentDeckId_idx" ON "FlashcardDeck"("parentDeckId");
CREATE INDEX IF NOT EXISTS "FlashcardDeck_classId_subjectId_idx" ON "FlashcardDeck"("classId", "subjectId");
CREATE INDEX IF NOT EXISTS "Flashcard_deckId_position_idx" ON "Flashcard"("deckId", "position");
CREATE INDEX IF NOT EXISTS "FlashcardReview_flashcardId_userId_reviewedAt_idx" ON "FlashcardReview"("flashcardId", "userId", "reviewedAt");
CREATE INDEX IF NOT EXISTS "FlashcardState_userId_nextReviewAt_idx" ON "FlashcardState"("userId", "nextReviewAt");
CREATE INDEX IF NOT EXISTS "FlashcardState_userId_status_idx" ON "FlashcardState"("userId", "status");
CREATE INDEX IF NOT EXISTS "Task_studentId_status_dueAt_idx" ON "Task"("studentId", "status", "dueAt");
CREATE INDEX IF NOT EXISTS "StudySession_studentId_plannedStartAt_idx" ON "StudySession"("studentId", "plannedStartAt");
CREATE INDEX IF NOT EXISTS "StudySession_studentId_status_plannedStartAt_idx" ON "StudySession"("studentId", "status", "plannedStartAt");
CREATE INDEX IF NOT EXISTS "WeakPoint_studentId_status_severityScore_idx" ON "WeakPoint"("studentId", "status", "severityScore");
CREATE INDEX IF NOT EXISTS "Essay_studentId_createdAt_idx" ON "Essay"("studentId", "createdAt");
CREATE INDEX IF NOT EXISTS "Essay_teacherId_status_createdAt_idx" ON "Essay"("teacherId", "status", "createdAt");
CREATE INDEX IF NOT EXISTS "GradingRubric_creatorId_subjectId_idx" ON "GradingRubric"("creatorId", "subjectId");
CREATE INDEX IF NOT EXISTS "EssayFeedback_essayId_createdAt_idx" ON "EssayFeedback"("essayId", "createdAt");
CREATE INDEX IF NOT EXISTS "AIGeneration_userId_createdAt_idx" ON "AIGeneration"("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "StudentGrade_studentId_capturedAt_idx" ON "StudentGrade"("studentId", "capturedAt");
CREATE INDEX IF NOT EXISTS "StudentGrade_studentId_subjectId_capturedAt_idx" ON "StudentGrade"("studentId", "subjectId", "capturedAt");
CREATE INDEX IF NOT EXISTS "FlashcardShare_ownerUserId_createdAt_idx" ON "FlashcardShare"("ownerUserId", "createdAt");
CREATE INDEX IF NOT EXISTS "NewsSelection_userId_sectionId_expiresAt_idx" ON "NewsSelection"("userId", "sectionId", "expiresAt");
COMMIT;
